/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mcreator.lilypad;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.EntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class LilypadModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();

	public LilypadModElements() {
		sounds.put(new ResourceLocation("lilypad", "suomalainen_kehtolaulu"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("lilypad", "suomalainen_kehtolaulu")));
		sounds.put(new ResourceLocation("lilypad", "norway"), new net.minecraft.util.SoundEvent(new ResourceLocation("lilypad", "norway")));
		sounds.put(new ResourceLocation("lilypad", "sadway"), new net.minecraft.util.SoundEvent(new ResourceLocation("lilypad", "sadway")));
		sounds.put(new ResourceLocation("lilypad", "sunrise_at_denmark"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("lilypad", "sunrise_at_denmark")));
		sounds.put(new ResourceLocation("lilypad", "factorial"), new net.minecraft.util.SoundEvent(new ResourceLocation("lilypad", "factorial")));
		sounds.put(new ResourceLocation("lilypad", "hidden_den"), new net.minecraft.util.SoundEvent(new ResourceLocation("lilypad", "hidden_den")));
		sounds.put(new ResourceLocation("lilypad", "lemuria"), new net.minecraft.util.SoundEvent(new ResourceLocation("lilypad", "lemuria")));
		sounds.put(new ResourceLocation("lilypad", "moon_2"), new net.minecraft.util.SoundEvent(new ResourceLocation("lilypad", "moon_2")));
		sounds.put(new ResourceLocation("lilypad", "estonian_reliquary"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("lilypad", "estonian_reliquary")));
		sounds.put(new ResourceLocation("lilypad", "colossal.death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("lilypad", "colossal.death")));
		sounds.put(new ResourceLocation("lilypad", "colossal.ambient"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("lilypad", "colossal.ambient")));
		sounds.put(new ResourceLocation("lilypad", "colossal.hurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("lilypad", "colossal.hurt")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("lilypad").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == LilypadModElements.ModElement.class)
						elements.add((LilypadModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(LilypadModElements.ModElement::initElements);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}

	private int messageID = 0;

	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		LilypadMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}

	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}

		protected final LilypadModElements elements;
		protected final int sortid;

		public ModElement(LilypadModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
